// Copyright (C) 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.caja.tools;

import java.io.IOException;
import java.util.List;

import com.google.caja.util.Join;
import com.google.caja.util.Lists;

import junit.framework.TestCase;

public class EnumsToJsTest extends TestCase {
  public final void testGeneratedJavaScript() throws IOException {
    StringBuilder sb = new StringBuilder();
    List<Class<? extends Enum<?>>> classes = Lists.newArrayList();
    classes.add(Foo.class);
    classes.add(SomeLetters.class);

    new EnumsToJs().generateJavaScriptForEnums(classes, sb);

    assertEquals(
        Join.join(
            "\n",
            "// Autogenerated by com.google.caja.tools.EnumsToJs",
            "",
            "// From com.google.caja.tools.Foo",
            "var FOO = ['FOO', 'FOO_BAR', 'FOO2', 'foo'];",
            "var FOO$FOO = 0;",
            "var FOO$FOO_BAR = 1;",
            "var FOO$FOO2 = 2;",
            "var FOO$foo = 3;",
            "",
            "// From com.google.caja.tools.SomeLetters",
            "var SOME_LETTERS = ['X', 'Y', 'Z'];",
            "var SOME_LETTERS$X = 0;",
            "var SOME_LETTERS$Y = 1;",
            "var SOME_LETTERS$Z = 2;",
            ""),
        sb.toString());
  }
}

enum Foo {
  FOO,
  FOO_BAR,
  FOO2,
  foo,
  ;
}

enum SomeLetters {
  X,
  Y,
  Z,
  ;
}
